# Defines stages which are to be executed
stages:  
  - build
  - deploy

.deploy_template: &deploy_script_templ
  - git clone https://$GL_UPLOADER_USER:$GL_UPLOADER_PASSWORD@gitlab.consolinno-it.de/leafletfirmware/package-upload.git
  - ./package-upload/debupload.sh snapshot $PWD/build/$(ls build/ | grep .*.deb)


build:buster:
  image: lheiz/dc-armv7-nymea-d10
  stage: build
  script:
    - gosu root apt-get install -y git-buildpackage
    - gbp dch -S -a --snapshot-number=`date +"%s"` --ignore-branch
    - CONFIG_SITE=/etc/dpkg-cross/cross-config.armhf  gosu root dpkg-buildpackage -b -aarmhf -Pcross,nocheck && mkdir -p build && gosu root mv ../*.deb build
  artifacts:
    paths:
      - build/*.deb

deploy:
  stage: deploy
  image: debian:buster
  script:
    - *deploy_script_templ

